# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowDaftarUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowDaftarUser(object):
    def setupUi(self, windowDaftarUser):
        windowDaftarUser.setObjectName("windowDaftarUser")
        windowDaftarUser.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(windowDaftarUser)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 331, 131))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 200, 221, 41))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 300, 221, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 300, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        windowDaftarUser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(windowDaftarUser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        windowDaftarUser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(windowDaftarUser)
        self.statusbar.setObjectName("statusbar")
        windowDaftarUser.setStatusBar(self.statusbar)

        self.retranslateUi(windowDaftarUser)
        QtCore.QMetaObject.connectSlotsByName(windowDaftarUser)

    def retranslateUi(self, windowDaftarUser):
        _translate = QtCore.QCoreApplication.translate
        windowDaftarUser.setWindowTitle(_translate("windowDaftarUser", "MainWindow"))
        self.label.setText(_translate("windowDaftarUser", "Pendaftaran Rumah Sakit"))
        self.label_2.setText(_translate("windowDaftarUser", "Masukkan Username"))
        self.label_3.setText(_translate("windowDaftarUser", "Masukkan Password"))
        self.pushButton.setText(_translate("windowDaftarUser", "Kembali"))
        self.label_4.setText(_translate("windowDaftarUser", "Daftar Akun"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowDaftarUser = QtWidgets.QMainWindow()
    ui = Ui_windowDaftarUser()
    ui.setupUi(windowDaftarUser)
    windowDaftarUser.show()
    sys.exit(app.exec_())
