# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowLoginUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowLoginUser(object):
    def setupUi(self, windowLoginUser):
        windowLoginUser.setObjectName("windowLoginUser")
        windowLoginUser.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(windowLoginUser)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 331, 131))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 300, 221, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 300, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 200, 221, 41))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        windowLoginUser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(windowLoginUser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        windowLoginUser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(windowLoginUser)
        self.statusbar.setObjectName("statusbar")
        windowLoginUser.setStatusBar(self.statusbar)

        self.retranslateUi(windowLoginUser)
        QtCore.QMetaObject.connectSlotsByName(windowLoginUser)

    def retranslateUi(self, windowLoginUser):
        _translate = QtCore.QCoreApplication.translate
        windowLoginUser.setWindowTitle(_translate("windowLoginUser", "MainWindow"))
        self.label.setText(_translate("windowLoginUser", "Pendaftaran Rumah Sakit"))
        self.pushButton.setText(_translate("windowLoginUser", "Kembali"))
        self.label_3.setText(_translate("windowLoginUser", "Masukkan Password"))
        self.label_4.setText(_translate("windowLoginUser", "Login Akun"))
        self.label_5.setText(_translate("windowLoginUser", "Masukkan Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowLoginUser = QtWidgets.QMainWindow()
    ui = Ui_windowLoginUser()
    ui.setupUi(windowLoginUser)
    windowLoginUser.show()
    sys.exit(app.exec_())
